parameters:
#    hp_category.example.class: Hp\CategoryBundle\Example

services:
#    hp_category.example:
#        class: %hp_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
